apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  selector:
    matchLabels:
      app: vote
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote-container
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
              name: vote