apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rs
  labels:
    app: frontend
spec:
  template:
    metadata:
      name: nginx
      labels:
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      env: production
  replicas: 2